services:
    web:
        image: nginx:latest
        ports:
            - "8010:80"
        volumes:
            - ./conf.d:/etc/nginx/conf.d
            - ./app:/app
        depends_on:
            - php
        restart: always
        networks:
            mysite_network:
                aliases:
                    - mysite.local

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./app:/app
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - mysql
        restart: always
        networks:
            mysite_network:
                aliases:
                    - mysite.local

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'mystrongpassword'
            MYSQL_USER: 'myname'
            MYSQL_PASSWORD: 'mystrongpassword'
            MYSQL_DATABASE: 'mysite'
        volumes:
            - mysite:/var/lib/mysql
        ports:
            - "33061:3306"
        restart: always
        networks:
            - mysite_network

volumes:
    mysite: {}

networks:
    mysite_network:
        driver: bridge
